name: Run E2E Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install CI-only tools (start-server-and-test)
        run: npm install --no-save start-server-and-test

      - name: Build Angular Project
        run: npm run build

      - name: Run E2E Tests
        run: npm run e2e
