name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start Angular server
        run: npm start &
      
      - name: Wait for Angular server to be ready
        uses: softprops/wait-for@v1
        with:
          url: 'http://localhost:4200'
          timeout: '60'

      - name: Run Cypress tests
        run: npm run cypress:run
